### 데이터 인코딩

#### 레이블 인코딩(Label encoding)

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)  # items 값들 중 unique한 것들만 추출해서 숫자로 변환
labels = encoder.transform(items)   # items값들을 숫자로 변환
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
print('디코딩 원본 값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


#### 원핫 인코딩(One-Hot encoding)

In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
items = np.array(items)
items

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [5]:
items = np.array(items).reshape(-1,1)
items

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [6]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [7]:
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [8]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링(Feature scaling)

#### 표준화(standardization)
* StandardScaler : 개별 피처를 평균이 0이고 분산이 1인 값으로 변환
* 가우시안 정규 분포

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris


iris = load_iris()
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [10]:
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### 정규화(Normalization)
* MinMaxScaler

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print("feature들의 최솟값")
print(iris_df_scaled.min())
print("\nfeature들의 최댓값")
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 주의 사항

In [15]:
# fit_transform() 함수 사용 가능

from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

print(train_array,"\n")
print(test_array)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [19]:
scaler = MinMaxScaler()

scaler.fit(train_array) # 데이터의 최솟값이 0, 최댓값이 10으로 결정
train_scaled = scaler.transform(train_array)    # 1/10 scale로 train_array 데이터 변환
#print(train_array)
print("원본 train_array 데이터:",np.round(train_array.reshape(-1),2))
print("Scale된 train_array 데이터:",np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [20]:
scaler.fit(test_array)  # 데이터의 최솟값이 0, 최댓값이 5로 결정
test_scaled = scaler.transform(test_array)  # 1/5 scale로 test_array 데이터 변환

print("원본 test_array 데이터:",np.round(test_array.reshape(-1),2))
print("Scale된 test_array 데이터:",np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [22]:
scaler = MinMaxScaler()

scaler.fit(train_array) # 데이터의 최솟값이 0, 최댓값이 10으로 결정
train_scaled = scaler.transform(train_array)    # 1/10 scale로 train_array 데이터 변환
#print(train_array)
print("원본 train_array 데이터:",np.round(train_array.reshape(-1),2))
print("Scale된 train_array 데이터:",np.round(train_scaled.reshape(-1),2))

test_scaled = scaler.transform(test_array)  # 1/5 scale로 test_array 데이터 변환
print("\n원본 test_array 데이터:",np.round(test_array.reshape(-1),2))
print("Scale된 test_array 데이터:",np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


#### 기타(numpy->reshape())

In [27]:
import numpy as np

x = np.arange(12).reshape(3,4)
x.shape
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### reshape(-1,정수) : 행(row) 위치에 '-1'이 들어있을 경우

In [31]:
# 열 차원의 정수에 따라서 12개의 원소가 빠짐없이 배치될 수 있도록 함
# -1이 들어가 있는 행의 개수가 가변적으로 정해짐
a = x.reshape(-1,1)
print(a.shape)
print(a)

(12, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [32]:
a = x.reshape(-1,2)
print(a.shape)
print(a)

(6, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [33]:
a = x.reshape(-1,3)
print(a.shape)
print(a)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [34]:
a = x.reshape(-1,4)
print(a.shape)
print(a)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### reshape(정수,-1) : 열(column) 위치에 '-1'이 들어있을 경우

In [35]:
a = x.reshape(1,-1)
print(a.shape)
print(a)

(1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [36]:
a = x.reshape(2,-1)
print(a.shape)
print(a)

(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [37]:
a = x.reshape(3,-1)
print(a.shape)
print(a)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
a = x.reshape(4,-1)
print(a.shape)
print(a)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### reshape(-1)인 경우

In [39]:
a = x.reshape(-1)
print(a.shape)
print(a)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [40]:
a = x.reshape(1,-1)
print(a.shape)
print(a)

(1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


#### ValueError : cannot reshape array of size 12 into shape (5)

In [41]:
a = x.reshape(-1,5)
print(a.shape)
print(a)

ValueError: cannot reshape array of size 12 into shape (5)

In [42]:
a = x.reshape(7,1)
print(a.shape)
print(a)

ValueError: cannot reshape array of size 12 into shape (7,1)

#### ValueError : can only specify one unknow dimension

In [43]:
a = x.reshape(-1,-1)
print(a.shape)
print(a)

ValueError: can only specify one unknown dimension